services:
  frontend-service:
    build: .
    container_name: frontend-service
    ports:
      - "4200:80"
    environment:
      - MOVIE_SERVICE_URL=http://movie-service:8081/api/v1
      - REVIEW_SERVICE_URL=http://review-service:8082/api/v1
        #    depends_on:
        # - movie-service
        # - review-service
    networks:
      - bookmyseat-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  bookmyseat-network:
    external: true
